package errs

func errcheck() {
	fnWithError()
}
